#!/bin/bash


# Make sure only root can run our script
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Running SHA check against $1..."

T="$(date +%s)"
find $1 -xdev -type f -exec cshatag {} \; 2>> /etc/cshatag/log/cshatag.log 1> /dev/null
T="$(($(date +%s)-T))"

echo "DONE: ${T} seconds"
