#!/bin/bash

unset ENABLE_CPU DISABLE_CPU HELP LIST

while getopts 'e:d:hl' c
do
  case $c in
    e) ENABLE_CPU=$OPTARG ;;
    d) DISABLE_CPU=$OPTARG ;;
    h) HELP=TRUE ;;
    l) LIST=TRUE ;;
  esac
done

check_root() {
  if (( $EUID != 0 )); then
    echo "This operation can only be befored by root"
    exit
  fi
}

display_help() {
  echo "CPUd version 1.0"
  echo "Copyright 2020, Jason Whitehorn - BSD II Clause"
  echo "   (see https://github.com/jwhitehorn/linux_utils for more info)"
  echo ""
  echo "Usage: cpud [option] [cpu #]"
  echo ""
  echo "Options:"
  echo "   -d      Disable the specified CPU"
  echo "   -e      Enable the specified CPU"
  echo "   -l      List basic information about the CPU and their status"
  echo "   -h      Display this wonderful help"
  echo ""
  echo "Examples:"
  echo "cpud -d 3"
  echo "   The above disables the 4th CPU/core"
  echo "cpud -e 2"
  echo "   The above enables the 3rd CPU/core"
  echo "   (note: in both these examples, CPU/core numbering is 0 indexed)"
  echo ""
}

if [ -n "$ENABLE_CPU" ]; then
        check_root
        echo "Enabling CPU $ENABLE_CPU"
        echo 1 | tee /sys/devices/system/cpu/cpu$ENABLE_CPU/online > /dev/null
fi

if [ -n "$DISABLE_CPU" ]; then
  check_root
	echo "Disabling CPU $DISABLE_CPU"
	echo 0 | tee /sys/devices/system/cpu/cpu$DISABLE_CPU/online > /dev/null
fi

if [ -n "$HELP" ]; then
  display_help
fi

if [ -n "$LIST" ]; then
  lscpu
fi
